action:
  title: test env keyring
runtime:
  type: shell
  script: |
    echo "Main env:"
    env | grep "LAUNCHR"
    {{ .current_bin }} keyring:purge
    {{ .current_bin }} keyring:set storedsecret "my_secret"
    echo "Subprocess env:"
    {{ .current_bin }} example:subshell
    {{ .current_bin }} keyring:purge