name: Commit Workflow

on:
  push:
  workflow_dispatch:

jobs:
  no-tty-in-ci:
    name: Ensure no TTY if user does not need to input anything
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make deps build
          ls -lah bin/launchr
          ./bin/launchr keyring:login --url=http://***.git --username="***" --password="***" --keyring-passphrase="***"
          echo "***" > my_secret
          ./bin/launchr keyring:login --url=http://***.git --username="***" --password="***" --keyring-passphrase-file="my_secret"
          
          LAUNCHR_KEYRING_PASSPHRASE=mypassphrase ./bin/launchr example:shell
          echo "mypassphrase" > my_secret
          LAUNCHR_KEYRING_PASSPHRASE_FILE=my_secret ./bin/launchr example:shell

  commands-ok:
    name: Ensure main commands do not fail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make deps build
          ls -lah bin/launchr
          ./bin/launchr keyring:set vaultpass "myvaultpass" --keyring-passphrase "mypassphrase"
          ls -lah .launchr/keyring.yaml.age
          ./bin/launchr keyring:unset vaultpass --keyring-passphrase "mypassphrase"
          ls -lah .launchr/keyring.yaml.age

  go-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make lint

  go-tests:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make test

